---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starter-config-map
data:
  debugFlag: "135"
  keep: "3650"
---
apiVersion: v1
kind: Pod
metadata:
  name: starter-config-map-as-volume
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "export" ]
      envFrom:
        - configMapRef:
            name: starter-config-map
  restartPolicy: Never
